### PR TITLE
chore: add github action that builds the site and checks the build

### LINKED ISSUE #160: Add a GitHub action that builds the site
Recently we merged a pull request which made the site build fail because it contained a couple of small errors. We should probably add a GitHub action that builds the site and does a quick smoke test before we merge any PR

### PR DESCRIPTION
**Pull request by carlos-granados**
Fixes https://github.com/Behat/docs/issues/160

### CODE REVIEW

**Comment by carlos-granados** [comment]
@acoulton I created this PR but it seems that actions are not enabled for this repo 😞. It worked on a test a did on my fork. I guess we will need @everzet to enable actions here. Unless you can think of any other reason why this won't run here

**Comment by carlos-granados** [comment]
> @acoulton I created this PR but it seems that actions are not enabled for this repo 😞. It worked on a test a did on my fork. I guess we will need @everzet to enable actions here. Unless you can think of any other reason why this won't run here

Mmm, it is weird, if actions were disabled then the Actions tab would not show 🤔

**Comment by stof** [comment]
When adding a new workflow in a PR, it won't run for PRs coming from a fork (as there is no workflow triggered on PRs in the repo being the target of the PR)

**Comment by carlos-granados** [comment]
Ah, yes, of course. And this is not the first time I have had this... 🤦

**Comment by carlos-granados** [comment]
This is the workflow run in my fork: https://github.com/carlos-granados/behat-docs/actions/runs/11726804170

**Comment by stof** [comment]
Adding a new workflow is a case where it is simpler to put the feature branch in the main repo rather than contributing from a fork.

**Comment by acoulton** [comment]
The file itself looks good at a scan, if it is working in your fork I suggest we merge it and hopefully that should trigger a first run - as @stof says I think it's just because it's new. 

Either it will go green or nothing will happen so no major issue merging IMO 🤣

**Review by stof — APPROVED** [review]

**Comment by carlos-granados** [comment]
It did not work because the main brach here is not `master` 🤦  Let me add a fix

**Pull request merged**
