### PR TITLE
feature: Update Read the Docs integration and site features

### PR DESCRIPTION
**Pull request by acoulton**
A further iteration on updating / improving the Read the Docs configuration based on their recommendations / product docs - including highlighting the built-in site search on the site and generating a custom 404 page.

### CODE REVIEW

**Comment by acoulton** [comment]
This is currently available to preview on my fork's built PR version at https://ac-behat-docs-test--3.org.readthedocs.build/en/3/

**Comment by carlos-granados** [comment]
@acoulton I tested your built version and the new search does not seem to work (when you search it never finds any results). However it may not be due to your changes because the old search (available on the small dialog on the bottom right) does not work either. It does work on the Behat docs site

**Comment by acoulton** [comment]
@carlos-granados sorry I forgot to mention that the PR builds don't generate a search index so the UI works but the no results is expected https://docs.readthedocs.io/en/stable/guides/pull-requests.html

**Comment by carlos-granados** [comment]
@acoulton I tried to follow the instructions you posted to build the site locally but when I executed the last command to build the docs I got this error:
```
/usr/local/bin/python: No module named sphinx.__main__; 'sphinx' is a package and cannot be directly executed
```

**Comment by acoulton** [comment]
@carlos-granados hmm - I can't reproduce that. Were you running in a docker container, or on your local system python? I've just destroyed my docker container and spun it up again and it seems to be working for me...

I confess I know very little about python / pip and don't have python installed. I got mine working first time in the docker container by copying the docs / steps from RtD but I don't really know how pip works.

**Comment by carlos-granados** [comment]
@acoulton I tested by following the steps listed in the readme exactly. I started the docker container, ran the two commands to install the dependencies and then ran the command to generate the docs. Can you please share the place where you found these commands so that I can take a look and see if there is anything that I might be doing wrong?

**Comment by carlos-granados** [comment]
@acoulton ignore me, I was just being stupid. I was trying to run this in the `v3.0` branch, not your branch, so it was installing an old set of requirements. Once I moved to your branch all works fine

**Comment by acoulton** [comment]
@carlos-granados phew - I was just about to suggest that, as otherwise I had no ideas :laughing:

**Review by carlos-granados — APPROVED** [review]
Tested and works fine, the docs are good as well. Thanks @acoulton

**Comment by acoulton** [comment]
ps. the steps in the README are from the RtD build process logs - at the moment you have to look at builds on my fork to see them https://app.readthedocs.org/projects/ac-behat-docs-test/builds/26159093/ but once this is merged you'll be able to get them from the build logs for behat itself by following the readme links.

**Comment by ttomdewit** [comment]
I do not have time to run the entire build with Python, but it appears between the two of you it works fine. I did read the text in the docs and I approve those.

**Review by ttomdewit — APPROVED** [review]

**Pull request merged**
