### PR TITLE
Add a cookbook about accessing contexts from each other

### PR DESCRIPTION
**Pull request by stof**
Refs https://github.com/Behat/Behat/issues/558

### CODE REVIEW

**Comment by everzet** [comment]
:) I really didn't want to expose this functionality on public. I think this is legit case, but the one that could lead to fragile test suites if used without caution :)))

**Comment by stof** [comment]
Well, the thing is, this has been requested many times, especially by people coming from Behat 2.5 (and this is the reason why I'm not using Behat 3 at work yet myself btw). Maybe we should add another warning saying to use this with caution.

**Comment by everzet** [comment]
@stof agreed. I don't think punishing people is the way to teach them that there's a better way. We need to educate them about that better way in addition to providing a very simple solution as you shown (but with word of caution).

**Comment by Taluu** [comment]
:+1: also on this. And an even bigger :+1: on a word on the "right way"  (especially on cases such as "debug contexts", which would probably need other contexts to work)

**Comment by stof** [comment]
@everzet I will let you write the documentation about the better way, as you have more experience with Behat 3 than me, and so you probably know it better.

**Comment by everzet** [comment]
@stof fair enough :)

**Pull request merged**
