### PR TITLE
New structure for 3.0 as proposed in #80

### PR DESCRIPTION
**Pull request by legovaer**
This is the big PR for the new structure as proposed in #80 

The result of this PR can be checked on the project in [readthedocs](http://behat-docs.readthedocs.org/en/mvp1.0/)

### CODE REVIEW

**Comment by stof** [comment]
conflicts must be resolved

**Comment by legovaer** [comment]
I will create a new PR from legovaer/docs:v3.0 instead of this one.

**Comment by stof** [comment]
I think it would be great to avoid having all these merge commits in the history, especially as they are referencing PRs numbered in a different repo, which may make a mess in references when being in the Behat repo

**Comment by legovaer** [comment]
That would be better indeed. I'll try to fix that.

**Comment by stof** [comment]
@legovaer A `git rebase` would drop merge commits (and it will give you a chance to fix conflicts)

**Comment by legovaer** [comment]
@stof have a look at #85

**Pull request closed without merging**
