### PR TITLE
Suggestion of new structure

### PR DESCRIPTION
**Pull request by legovaer**
This is a first draft of a suggestion for the new structure of the Behat documentation. This PR is only used for discussing the structure and should never get merged into the official Behat/docs repository.

Feel free to comment!

The order of elements still needs to be adjusted, this is just a high level overview of content that should get inside the documentation.

### CODE REVIEW

**Comment by stof** [comment]
why creating a PR with a file in it which should never be merged instead of putting this in the discussion ?

**Comment by legovaer** [comment]
GitHub does not allow .rtf/.txt formats as an attachment in the comments. If we're going to discuss this structure, it would be easier to talk about line numbers. That's why I've created this PR.

**Comment by stof** [comment]
I'm not talking about using a txt file as attachment. I'm talking about putting it directly in comments.
I don't think line numbers are really relevant here. Each section has a number anyway in your proposal.

**Comment by legovaer** [comment]
I've added it to the comments of #80

**Pull request closed without merging**
