### PR TITLE
Fix link to What's in a Story article

### PR DESCRIPTION
**Pull request by kevin-f**

### CODE REVIEW

**Review by bocharsky-bw — APPROVED** [review]
👍

**Comment by uuf6429** [comment]
@carlos-granados @acoulton this PR looks good to me.

**Review by carlos-granados — APPROVED** [review]
I fixed the conflict with the changes merged from another branch. Should be ready to go

**Review by acoulton — APPROVED** [review]
Looks like the change to the domain got lost in the conflict resolution (the link needed to be changed to drop the `blog.` subdomain, as well as going https). I've fixed that now.

**Pull request merged**
