### PR TITLE
BDD with Symfony2 cookbook entry

### PR DESCRIPTION
**Pull request by cakper**
Hiya, could you please check my draft of Symfony2 cookbook entry :)

Thanks. Kacper.

### CODE REVIEW

**Comment by everzet** [comment]
I like the beginning. The idea is to show an example of developing feature with Symfony2 using Behat v3 via Symfony2Extension. Kinda the same way quick intro is structured.

**Comment by cakper** [comment]
Ah, ok :) Will keep improving :)

**Comment by cakper** [comment]
@everzet do you want me to start totally from scratch (assuming only standard distribution and Acme bundles are installed)? And then develop some feature with Behat + Mink + Symfony2Extension?

**Comment by everzet** [comment]
@cakper that would be awesome :)

**Comment by stof** [comment]
The new page needs to be included in a toctree (see the sphinx warning triggering a build failure on Travis)

**Comment by cakper** [comment]
@stof thanks! :) will do once I finish the whole doc :)

**Comment by stof** [comment]
@cakper well, adding it in the toctree will allow you to see whether there are other issues in your contributions (sphinx stops at the first error, so you would not see other ones). So it is probably better to add it without waiting the end

**Pull request closed without merging**
